## Sklearn的標準化

In [1]:
import pandas as pd
import numpy as np
import io
import requests

url = "https://raw.githubusercontent.com/johnny12150/Data_Analytics_Course/master/Lecture%202/Data_and_Images/Batting.csv"
s=requests.get(url).content
PlayerDF = pd.read_csv(io.StringIO(s.decode('utf-8')))

### 1. StandardScaler

In [ ]:
from sklearn import preprocessing
# 將StandardScaler後的結果縮小至0與1的間隔範圍內
minMaxScale = preprocessing.MinMaxScaler(feature_range=(0, 1))
X = minMaxScale.fit_transform(PlayerDF[['yearID']])

# 確保列印所有的值出來，inf代表infinity，預設是nan
# np.set_printoptions(threshold=np.inf)
X

In [ ]:
scaler.transform(PlayerDF[['yearID']])

### 2. MinMaxScaler

In [2]:
from sklearn import preprocessing
# 將StandardScaler後的結果縮小至0與1的間隔範圍內
minMaxScale = preprocessing.MinMaxScaler(feature_range=(0, 1))
# 將scaler fit上training data
X = minMaxScale.fit_transform(PlayerDF[['yearID']])

# 確保列印所有的值出來，inf代表infinity，預設是nan
# np.set_printoptions(threshold=np.inf)
X

array([[0.],
       [0.],
       [0.],
       ...,
       [1.],
       [1.],
       [1.]])

#### 測試新的數值使用同個標準化物件

In [6]:
New_input = [[1872]]
# 使用以training data作為依據的sclaer，來轉化新的資料
New_outcome = minMaxScale.transform(New_input)
New_outcome

array([[0.00689655]])

#### 列出訓練用資料的縮放因素 (每個值縮放時所乘上的值)
https://www.cnblogs.com/chaosimple/p/4153167.html

In [7]:
minMaxScale.scale_

array([0.00689655])

In [8]:
minMaxScale.min_

array([-12.90344828])