## Save Python Object

In [1]:
import pandas as pd
import numpy as np
import io
import requests

url = "https://raw.githubusercontent.com/johnny12150/Data_Analytics_Course/master/Lecture%202/Data_and_Images/Batting.csv"
s=requests.get(url).content
PlayerDF = pd.read_csv(io.StringIO(s.decode('utf-8')))

#### 標準化

In [11]:
from sklearn import preprocessing
# 將StandardScaler後的結果縮小至0與1的間隔範圍內
minMaxScale = preprocessing.MinMaxScaler(feature_range=(0, 1))
X = minMaxScale.fit_transform(PlayerDF[['yearID']])

# 確保列印所有的值出來，inf代表infinity，預設是nan
# np.set_printoptions(threshold=np.inf)
X

array([[0.],
       [0.],
       [0.],
       ...,
       [1.],
       [1.],
       [1.]])

In [8]:
from sklearn.preprocessing import StandardScaler
# 將scaler綁上訓練用資料
scaler = preprocessing.StandardScaler().fit(PlayerDF[['yearID']])
scaler

StandardScaler(copy=True, with_mean=True, with_std=True)

In [9]:
scaler.transform(PlayerDF[['yearID']])

array([[-2.40019699],
       [-2.40019699],
       [-2.40019699],
       ...,
       [ 1.33152005],
       [ 1.33152005],
       [ 1.33152005]])

In [15]:
minMaxScale.fit_transform(scaler.transform(PlayerDF[['yearID']]))

array([[0.],
       [0.],
       [0.],
       ...,
       [1.],
       [1.],
       [1.]])

#### 測試新的數值使用同個標準化物件

In [27]:
New_input = [[1875]]
New_outcome = minMaxScale.fit_transform(New_input)
New_outcome

array([[0.]])

In [28]:
scaler.transform(New_input)

array([[-2.40019699]])

In [21]:
print(minMaxScale.fit_transform(scaler.transform([[1975]])))
print(scaler.transform([[1875]]))

[[0.]]
[[-2.29725307]]


In [22]:
minMaxScale.scale_

array([1.])

### 儲存方式

以下三種儲存方式的差異，主要在於讀取儲存的物件所需的時間

### 1. pickle

In [ ]:
import pickle

### 2. joblib

### 3. cPickle