In [2]:
import numpy as np
import pandas as pd
import matplotlib as plt

### arange()
arange([start,] stop[, step,], dtype=None) 根據start與stop指定的範圍以及step設定的步長，生成一個ndarray。

In [3]:
import time
size = 100000
a = np.arange(size)
b = np.arange(size)

start = time.time()
result_arr = a * b 
print('time spent: ', (time.time()-start))

time spent:  0.0013778209686279297


In [5]:
a

array([    0,     1,     2, ..., 99997, 99998, 99999])

### np.reshape(row, col)

In [8]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [9]:
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [12]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### 產生0-1的亂數

In [13]:
np.random.rand(10)

array([0.55437458, 0.98222171, 0.94270777, 0.10563561, 0.04894931,
       0.95167955, 0.94675072, 0.59298344, 0.72994928, 0.19186964])

### 產生介於指定範圍內的亂數

In [16]:
np.random.randint(1, 10, 5)

array([9, 2, 8, 7, 7])

In [15]:
np.arange(9).reshape(3,3)[1,1]

4

In [19]:
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### 轉置T

In [20]:
np.arange(1,10).reshape(3,3).T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

### flatten

In [21]:
# 以column
np.arange(1,10).reshape(3,3).flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
# 以row
np.arange(1,10).reshape(3,3).flatten('F')

array([1, 4, 7, 2, 5, 8, 3, 6, 9])

### 加減乘除

In [26]:
%%time
size = 100000
a1 = np.arange(size)
b1 = np.arange(size)

CPU times: user 689 µs, sys: 455 µs, total: 1.14 ms
Wall time: 617 µs


In [27]:
%%time
a1 + b1

CPU times: user 300 µs, sys: 56 µs, total: 356 µs
Wall time: 233 µs


array([     0,      2,      4, ..., 199994, 199996, 199998])

In [28]:
%%time
np.add(a1, b1)

CPU times: user 728 µs, sys: 571 µs, total: 1.3 ms
Wall time: 520 µs


array([     0,      2,      4, ..., 199994, 199996, 199998])

In [29]:
%%time
# 使用python內建的function進行np array相乘
a1 * b1

CPU times: user 831 µs, sys: 662 µs, total: 1.49 ms
Wall time: 606 µs


array([         0,          1,          4, ..., 9999400009, 9999600004,
       9999800001])

In [30]:
%%time
np.multiply(a1, b1)

CPU times: user 775 µs, sys: 478 µs, total: 1.25 ms
Wall time: 547 µs


array([         0,          1,          4, ..., 9999400009, 9999600004,
       9999800001])

In [31]:
# list to array 
list = [1,2,3]
np.array(list)

array([1, 2, 3])

In [32]:
# array to list
np.array(list).tolist()

[1, 2, 3]

In [34]:
x = np.random.randint(5, 60, 10)
print(x)
# 回傳index值
np.where(x > 30)

[44 38 34 47  5 28 26 50  9 17]


(array([0, 1, 2, 3, 7]),)

In [35]:
x[np.where(x > 30)]

array([44, 38, 34, 47, 50])

## EX01:

In [64]:
practice_arr = np.arange(1, 65).reshape(16, 4).T
practice_flat = practice_arr.flatten('F')
practice_reshape = practice_flat.reshape(8,8)
practice_zeros = np.zeros((8,2))
practice = np.concatenate([practice_zeros, practice_reshape], axis=1)
# row = 7, col = 5
np.where(practice == 60)

(array([7]), array([5]))

### 範例冰與火

In [76]:
df = pd.read_csv('newcharacter-deaths.csv')
df.head()

Name      Allegiances  Death Year  Book of Death  \
0           Addam Marbrand        Lannister         NaN            NaN   
1  Aegon Frey (Jinglebell)             None       299.0            3.0   
2          Aegon Targaryen  House Targaryen         NaN            NaN   
3            Adrack Humble    House Greyjoy       300.0            5.0   
4           Aemon Costayne        Lannister         NaN            NaN   

   Death Chapter  Book Intro Chapter  Gender  Nobility  GoT  CoK  SoS  FfC  \
0            NaN                56.0       1         1    1    1    1    1   
1           51.0                49.0       1         1    0    0    1    0   
2            NaN                 5.0       1         1    0    0    0    0   
3           20.0                20.0       1         1    0    0    0    0   
4            NaN                 NaN       1         1    0    0    1    0   

   DwD  Age  
0    0   41  
1    0   22  
2    1  NaN  
3    1   18  
4    0  73*

In [77]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 917 entries, 0 to 916
Data columns (total 14 columns):
Name                  917 non-null object
Allegiances           917 non-null object
Death Year            305 non-null float64
Book of Death         307 non-null float64
Death Chapter         299 non-null float64
Book Intro Chapter    905 non-null float64
Gender                917 non-null int64
Nobility              917 non-null int64
GoT                   917 non-null int64
CoK                   917 non-null int64
SoS                   917 non-null int64
FfC                   917 non-null int64
DwD                   917 non-null int64
Age                   865 non-null object
dtypes: float64(4), int64(7), object(3)
memory usage: 100.4+ KB


In [79]:
df.isnull().sum()

Name                    0
Allegiances             0
Death Year            612
Book of Death         610
Death Chapter         618
Book Intro Chapter     12
Gender                  0
Nobility                0
GoT                     0
CoK                     0
SoS                     0
FfC                     0
DwD                     0
Age                    52
dtype: int64

## EX02:鐵達尼號data cleaning

In [37]:
titanic_df =pd.read_csv('titanic.csv')
titanic_df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [44]:
titanic_df_select = titanic_df
# 大寫轉小寫
titanic_df_select.columns = titanic_df_select.columns.str.lower()
titanic_df_select = titanic_df_select[['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare','embarked']]
titanic_df_select.head()

survived  pclass     sex   age  sibsp  parch     fare embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

In [46]:
pd.get_dummies(titanic_df_select['sex']).head()

female  male
0       0     1
1       1     0
2       1     0
3       1     0
4       0     1

In [73]:
from sklearn import preprocessing
def encode_features(df):
    features = ['sex']
    for feature in features:
        le = preprocessing.LabelEncoder()
        le = le.fit(df[feature])
        df[feature] = le.transform(df[feature])
        one_hot = preprocessing.OneHotEncoder()
        ohe = one_hot.fit(df[[feature]])
        feature_array = ohe.transform(df[[feature]]).toarray()
        feature_labels = le.classes_
        one_hot_features = pd.DataFrame(feature_array, columns=feature_labels)
        df = pd.concat([df, one_hot_features], axis=1)
        df = df.drop(feature, axis=1)
    return df

encode_features(titanic_df_select).head()

/anaconda3/lib/python3.5/site-packages/ipykernel_launcher.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys


survived  pclass   age  sibsp  parch     fare embarked    0    1
0         0       3  22.0      1      0   7.2500        S  0.0  1.0
1         1       1  38.0      1      0  71.2833        C  1.0  0.0
2         1       3  26.0      0      0   7.9250        S  1.0  0.0
3         1       1  35.0      1      0  53.1000        S  1.0  0.0
4         0       3  35.0      0      0   8.0500        S  0.0  1.0

In [88]:
def gender_detect(sex):
    if sex == 'male':
        return 0
    else:
        return 1

titanic_df['sex'].apply(gender_detect)

0       0
1       1
2       1
3       1
4       0
5       0
6       0
7       0
8       1
9       1
10      1
11      1
12      0
13      0
14      1
15      1
16      0
17      0
18      1
19      1
20      0
21      0
22      1
23      0
24      1
25      1
26      0
27      0
28      1
29      0
       ..
1279    0
1280    0
1281    0
1282    1
1283    0
1284    0
1285    0
1286    1
1287    0
1288    1
1289    0
1290    0
1291    1
1292    0
1293    1
1294    0
1295    0
1296    0
1297    0
1298    0
1299    1
1300    1
1301    1
1302    1
1303    1
1304    0
1305    1
1306    0
1307    0
1308    0
Name: sex, Length: 1309, dtype: int64

## check null

In [66]:
titanic_df_select.isnull().sum()

survived      0
pclass        0
sex           0
age         263
sibsp         0
parch         0
fare          1
embarked      2
dtype: int64

In [74]:
titanic_df_select['age'].mean()

29.881137667304014

In [75]:
titanic_df_select['age'].fillna(titanic_df_select['age'].mean())

0       22.000000
1       38.000000
2       26.000000
3       35.000000
4       35.000000
5       29.881138
6       54.000000
7        2.000000
8       27.000000
9       14.000000
10       4.000000
11      58.000000
12      20.000000
13      39.000000
14      14.000000
15      55.000000
16       2.000000
17      29.881138
18      31.000000
19      29.881138
20      35.000000
21      34.000000
22      15.000000
23      28.000000
24       8.000000
25      38.000000
26      29.881138
27      19.000000
28      29.881138
29      29.881138
          ...    
1279    21.000000
1280     6.000000
1281    23.000000
1282    51.000000
1283    13.000000
1284    47.000000
1285    29.000000
1286    18.000000
1287    24.000000
1288    48.000000
1289    22.000000
1290    31.000000
1291    30.000000
1292    38.000000
1293    22.000000
1294    17.000000
1295    43.000000
1296    20.000000
1297    23.000000
1298    50.000000
1299    29.881138
1300     3.000000
1301    29.881138
1302    37.000000
1303    28