In [11]:
import pandas as pd
import numpy as np
import io
import requests

url = "https://raw.githubusercontent.com/johnny12150/Data_Analytics_Course/master/Lecture%202/Data_and_Images/Batting.csv"
s=requests.get(url).content
PlayerDF = pd.read_csv(io.StringIO(s.decode('utf-8')))

In [2]:
PlayerDF.head(5)

playerID  yearID  stint teamID lgID   G   AB   R   H  2B  ...    RBI   SB  \
0  abercda01    1871      1    TRO  NaN   1    4   0   0   0  ...    0.0  0.0   
1   addybo01    1871      1    RC1  NaN  25  118  30  32   6  ...   13.0  8.0   
2  allisar01    1871      1    CL1  NaN  29  137  28  40   4  ...   19.0  3.0   
3  allisdo01    1871      1    WS3  NaN  27  133  28  44  10  ...   27.0  1.0   
4  ansonca01    1871      1    RC1  NaN  25  120  29  39  11  ...   16.0  6.0   

    CS  BB   SO  IBB  HBP  SH  SF  GIDP  
0  0.0   0  0.0  NaN  NaN NaN NaN   NaN  
1  1.0   4  0.0  NaN  NaN NaN NaN   NaN  
2  1.0   2  5.0  NaN  NaN NaN NaN   NaN  
3  1.0   0  2.0  NaN  NaN NaN NaN   NaN  
4  2.0   2  1.0  NaN  NaN NaN NaN   NaN  

[5 rows x 22 columns]

### 處理類別資料

#### Step 1 Label Encode

In [7]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
le = LabelEncoder()
teamID_one_hot = le.fit_transform(PlayerDF['teamID'])
teamID_one_hot

array([135, 110,  38, ...,  34, 115, 115])

In [8]:
# one-hot後的長度 (相當於資料總數)
len(teamID_one_hot)

102816

In [15]:
# 計算nd array的unique數量
count_unique = np.bincount(teamID_one_hot)
count_unique

array([  17,  337,  880, 2110, 2565,  122,   26,   48,  197,   36,   19,
         62,   67,  192,   36, 4328,   26,   90,  112,   22,   74, 2160,
         17,   58,   25, 2223,   17,   25,   59, 1315,   11,   30, 4279,
         58, 4863,   16,   35, 4540,   25,  106,   48,  252,   32,   66,
       4500,   21,   76,  149,   23,   23, 1126, 4216,  181,   16,  849,
         18,   27, 2234,   29,   13,   35,   66,   28,  572,   52, 2013,
         46,   17,   51,   11,  717, 2401,   29,  226,  249,  247,   12,
        844, 2168,  467,   15,   16, 1060,   26,   12, 1479,   28,   25,
       2327,   63,   24,  101, 4273, 2338,   17, 2096,   66,   42,   12,
        248, 1832, 4770,   21,   16,   29, 4722,  130,  112,   62,   17,
         11,   20,   19, 2065,   53, 1725, 2345,   12,   13,   27,  217,
         50, 1752,   50, 4668,   22,   11,   18,   30,  857, 1988,   21,
         20, 1684,   69,   24,  806,   20,   60, 2069,  430,   28,   14,
         15,   19,   25,  113,   38,   51])

In [16]:
ii = np.nonzero(count_unique)[0]
ii

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148])

In [20]:
# method 01 印出各個值出現的次數
list(zip(ii,count_unique[ii]))

[(0, 17),
 (1, 337),
 (2, 880),
 (3, 2110),
 (4, 2565),
 (5, 122),
 (6, 26),
 (7, 48),
 (8, 197),
 (9, 36),
 (10, 19),
 (11, 62),
 (12, 67),
 (13, 192),
 (14, 36),
 (15, 4328),
 (16, 26),
 (17, 90),
 (18, 112),
 (19, 22),
 (20, 74),
 (21, 2160),
 (22, 17),
 (23, 58),
 (24, 25),
 (25, 2223),
 (26, 17),
 (27, 25),
 (28, 59),
 (29, 1315),
 (30, 11),
 (31, 30),
 (32, 4279),
 (33, 58),
 (34, 4863),
 (35, 16),
 (36, 35),
 (37, 4540),
 (38, 25),
 (39, 106),
 (40, 48),
 (41, 252),
 (42, 32),
 (43, 66),
 (44, 4500),
 (45, 21),
 (46, 76),
 (47, 149),
 (48, 23),
 (49, 23),
 (50, 1126),
 (51, 4216),
 (52, 181),
 (53, 16),
 (54, 849),
 (55, 18),
 (56, 27),
 (57, 2234),
 (58, 29),
 (59, 13),
 (60, 35),
 (61, 66),
 (62, 28),
 (63, 572),
 (64, 52),
 (65, 2013),
 (66, 46),
 (67, 17),
 (68, 51),
 (69, 11),
 (70, 717),
 (71, 2401),
 (72, 29),
 (73, 226),
 (74, 249),
 (75, 247),
 (76, 12),
 (77, 844),
 (78, 2168),
 (79, 467),
 (80, 15),
 (81, 16),
 (82, 1060),
 (83, 26),
 (84, 12),
 (85, 1479),
 (86, 28),

In [19]:
# method 02 印出各個值出現的次數
np.vstack((ii,count_unique[ii])).T

array([[   0,   17],
       [   1,  337],
       [   2,  880],
       [   3, 2110],
       [   4, 2565],
       [   5,  122],
       [   6,   26],
       [   7,   48],
       [   8,  197],
       [   9,   36],
       [  10,   19],
       [  11,   62],
       [  12,   67],
       [  13,  192],
       [  14,   36],
       [  15, 4328],
       [  16,   26],
       [  17,   90],
       [  18,  112],
       [  19,   22],
       [  20,   74],
       [  21, 2160],
       [  22,   17],
       [  23,   58],
       [  24,   25],
       [  25, 2223],
       [  26,   17],
       [  27,   25],
       [  28,   59],
       [  29, 1315],
       [  30,   11],
       [  31,   30],
       [  32, 4279],
       [  33,   58],
       [  34, 4863],
       [  35,   16],
       [  36,   35],
       [  37, 4540],
       [  38,   25],
       [  39,  106],
       [  40,   48],
       [  41,  252],
       [  42,   32],
       [  43,   66],
       [  44, 4500],
       [  45,   21],
       [  46,   76],
       [  47,

In [21]:
# 把轉完的label加到DF
PlayerDF['team_label'] = teamID_one_hot
PlayerDF.head(5)

playerID  yearID  stint teamID lgID   G   AB   R   H  2B     ...       SB  \
0  abercda01    1871      1    TRO  NaN   1    4   0   0   0     ...      0.0   
1   addybo01    1871      1    RC1  NaN  25  118  30  32   6     ...      8.0   
2  allisar01    1871      1    CL1  NaN  29  137  28  40   4     ...      3.0   
3  allisdo01    1871      1    WS3  NaN  27  133  28  44  10     ...      1.0   
4  ansonca01    1871      1    RC1  NaN  25  120  29  39  11     ...      6.0   

    CS  BB   SO  IBB  HBP  SH  SF  GIDP  team_label  
0  0.0   0  0.0  NaN  NaN NaN NaN   NaN         135  
1  1.0   4  0.0  NaN  NaN NaN NaN   NaN         110  
2  1.0   2  5.0  NaN  NaN NaN NaN   NaN          38  
3  1.0   0  2.0  NaN  NaN NaN NaN   NaN         141  
4  2.0   2  1.0  NaN  NaN NaN NaN   NaN         110  

[5 rows x 23 columns]

#### Step2 One Hot Encode

In [24]:
one_hot = OneHotEncoder()
teamID_feature_array = one_hot.fit_transform(PlayerDF[['team_label']]).toarray()
feature_labels = list(le.classes_)
list(le.classes_)

['ALT',
 'ANA',
 'ARI',
 'ATL',
 'BAL',
 'BFN',
 'BFP',
 'BL1',
 'BL2',
 'BL3',
 'BL4',
 'BLA',
 'BLF',
 'BLN',
 'BLU',
 'BOS',
 'BR1',
 'BR2',
 'BR3',
 'BR4',
 'BRF',
 'BRO',
 'BRP',
 'BS1',
 'BS2',
 'BSN',
 'BSP',
 'BSU',
 'BUF',
 'CAL',
 'CH1',
 'CH2',
 'CHA',
 'CHF',
 'CHN',
 'CHP',
 'CHU',
 'CIN',
 'CL1',
 'CL2',
 'CL3',
 'CL4',
 'CL5',
 'CL6',
 'CLE',
 'CLP',
 'CN1',
 'CN2',
 'CN3',
 'CNU',
 'COL',
 'DET',
 'DTN',
 'ELI',
 'FLO',
 'FW1',
 'HAR',
 'HOU',
 'HR1',
 'IN1',
 'IN2',
 'IN3',
 'IND',
 'KC1',
 'KC2',
 'KCA',
 'KCF',
 'KCN',
 'KCU',
 'KEO',
 'LAA',
 'LAN',
 'LS1',
 'LS2',
 'LS3',
 'MIA',
 'MID',
 'MIL',
 'MIN',
 'ML1',
 'ML2',
 'ML3',
 'ML4',
 'MLA',
 'MLU',
 'MON',
 'NEW',
 'NH1',
 'NY1',
 'NY2',
 'NY3',
 'NY4',
 'NYA',
 'NYN',
 'NYP',
 'OAK',
 'PH1',
 'PH2',
 'PH3',
 'PH4',
 'PHA',
 'PHI',
 'PHN',
 'PHP',
 'PHU',
 'PIT',
 'PRO',
 'PT1',
 'PTF',
 'PTP',
 'RC1',
 'RC2',
 'RIC',
 'SDN',
 'SE1',
 'SEA',
 'SFN',
 'SL1',
 'SL2',
 'SL3',
 'SL4',
 'SL5',
 'SLA',
 'SLF',
 'SLN',


In [25]:
team_features = pd.DataFrame(teamID_feature_array, columns=feature_labels)

In [26]:
team_features.head(5)

ALT  ANA  ARI  ATL  BAL  BFN  BFP  BL1  BL2  BL3 ...   WS1  WS2  WS3  WS4  \
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0  0.0   
1  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0  0.0   
2  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0  0.0   
3  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  1.0  0.0   
4  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0  0.0   

   WS5  WS6  WS7  WS8  WS9  WSU  
0  0.0  0.0  0.0  0.0  0.0  0.0  
1  0.0  0.0  0.0  0.0  0.0  0.0  
2  0.0  0.0  0.0  0.0  0.0  0.0  
3  0.0  0.0  0.0  0.0  0.0  0.0  
4  0.0  0.0  0.0  0.0  0.0  0.0  

[5 rows x 149 columns]

In [27]:
NewPlayerDF = pd.concat([PlayerDF, team_features], axis=1)
NewPlayerDF.head(5)

playerID  yearID  stint teamID lgID   G   AB   R   H  2B ...   WS1  WS2  \
0  abercda01    1871      1    TRO  NaN   1    4   0   0   0 ...   0.0  0.0   
1   addybo01    1871      1    RC1  NaN  25  118  30  32   6 ...   0.0  0.0   
2  allisar01    1871      1    CL1  NaN  29  137  28  40   4 ...   0.0  0.0   
3  allisdo01    1871      1    WS3  NaN  27  133  28  44  10 ...   0.0  0.0   
4  ansonca01    1871      1    RC1  NaN  25  120  29  39  11 ...   0.0  0.0   

   WS3  WS4  WS5  WS6  WS7  WS8  WS9  WSU  
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
1  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
2  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
3  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
4  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  

[5 rows x 172 columns]

### 直接用np get_dummies()取代step1 + step2